import Head from 'next/head'
import styles from '../../styles/Home.module.css'


const Projects = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://kaunda-a.github.io/Ndumiso_Banda_resume/">My Portfolio!</a>
        </h1>

        <p className={styles.description}>
          Student and Aspiring Web Developer{' '}
          <code className={styles.code}>resume</code>
        </p>

        <div className={styles.grid}>
          <a href="https://kaunda-a.github.io/Ndumiso_Banda_resume/" className={styles.card}>
            <h2>My resume &rarr;</h2>
            <p>Find out in-depth about me.</p>
          </a>

          <a href="https://github.com/dukeow8/BombCell.git" className={styles.card}>
            <h2>BombCell React-App &rarr;</h2>
            <p>This project was bootstrapped with Create React App.</p>
          </a>

          <a href="https://github.com/dukeow8/itunes-search.git" className={styles.card}>
            <h2>itunes-search  &rarr;</h2>
            <p>A website designed to search complete iTunes Store for anything from Apps, Artists, Songs to Podcasts.!</p>
          </a>

        </div>
      </main>
    </div>
  )
}

export default Projects;
